### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gitjoost**
Added P0, P1 and Photon SMD footprints. Renamed photon.kicad_mod to photon_tht.kicad_mod. Updated readme.md

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks @gitjoost for your PR!

Would you mind rotating and positioning the Photon SMD footprint so that it matches the THT version? That makes it possible to switch between the two versions without breaking the layout.

**Review by dbrgn — COMMENTED** [review]
Thanks for the change!

- Regarding these pads below the Photon, are they documented somewhere?
- Your keepout area is a bit smaller on the SMD version than on the THT version. Should they match?
- On your keepout area, you write "Antenna area, route no signals, no pwr / gnd planes". But a ground plane is actually good, to keep away interference, isn't it? On the THT version it says "ground plane and signal keep out recommendedon all layers". I copied that from some Particle docs IIRC.
- Regarding the reference, shouldn't they all be `U?` instead of `> Name` or `U2`? (I just noticed that the original THT footprint has this problem too...)

**Comment by dbrgn** [comment]
Oh, and I noticed that if you put the THT and SMD version over each other, the pins still don't match:

img

If you could move it so that the origin (the (0, 0) coordinates) matches the THT footprint, it has the great advantage that the footprints can be swapped without re-routing.

**Comment by gitjoost** [comment]
Sorry, trying to accommodate the changes while doing other things ... never good ;-)  Answering your questions and a few of my own:

1. See here for P1 data sheet: https://docs.particle.io/datasheets/p1-datasheet/
2. The keep out area is not well defined by particle (no dimensions) so small differences should not be a problem. That said, it is probably better/nicer to match these. I'll do that.
3. No a ground plane would not be good at all. Yes antenna's in general need 'a ground' but one that is design for the antenna, not a plane that runs close like this. It would create a capacitive load and a shield at the same time. I've got a board designed by a co-worker with that exact problem...
4. Not sure about that name; U? gets resolved to U<number> by  eeschema.
5. How did you align/attempt to align the foot prints? I.e., what was your reference point? I can easily align the pads but there are some differences with the outline. Some of my work was a little sloppy, will correct that. But the USB connector on the original _tht part is sticking out too much. Not a big deal but just saying.
6. When I bring in the original photon_tht part on a pcb, its origins are set in the middle, exactly as I did mine. I've got no problem changing but am not sure where you had it/how to check for that (besides going into the file directly).

**Comment by dbrgn** [comment]
> See here for P1 data sheet: https://docs.particle.io/datasheets/p1-datasheet/

Unless I'm misunderstanding you: That's the P1. What about the Photon?

> No a ground plane would not be good at all. Yes antenna's in general need 'a ground' but one that is design for the antenna, not a plane that runs close like this. 

Ah, of course. I mis-read my own comment - it's "ground plane (and signal) keep out recommended", not "ground plane (and signal keep out) recommended". If you want you can change the text on the THT version so it matches.

> Not sure about that name; U? gets resolved to U by eeschema.

Hm, maybe the text doesn't matter and is overwritten anyways when linked with a symbol.

> How did you align/attempt to align the foot prints? I.e., what was your reference point?

When you add a footprint to a PCB, you can see a small blue crosshair in the middle of it. If I understand KiCad correctly, that's the (0, 0) coordinate origin when editing the footprint.

> When I bring in the original photon_tht part on a pcb, its origins are set in the middle, exactly as I did mine.

If you look at the THT design, the pins 7 and 18 line up with the y-coordinate 0. You probably just have to move everything up by 50 mils.

**Comment by gitjoost** [comment]
Photon datasheet; https://docs.particle.io/datasheets/photon-datasheet/  SMD footprint is somewhere halfway down the page.   I'll true up the THT and SMD footprints in the coming week.

**Comment by dbrgn** [comment]
> Photon datasheet; https://docs.particle.io/datasheets/photon-datasheet/ SMD footprint is somewhere halfway down the page.

Ah, I see :)

**Comment by gitjoost** [comment]
@dbrgn Had a chance to check it?

**Comment by dbrgn** [comment]
@gitjoost thanks for the reminder. looks good now, thanks for your PR!

**Pull request merged**
